local_costmap:
  global_frame: $(arg odom_frame)
#  global_frame: /odom_combined
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.05 #0.05
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
